apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapplication-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapplication
  template:
    metadata:
      labels:
        app: myapplication
    spec:
      containers:
        - name: myapplication
          image: srikanthmadhavarapu/application:1.0.0-7
          resources:
            limits:
              cpu: "500m"
              memory: "256mi"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 8080
