apiVersion: v1
kind: Service
metadata:
  name: myapplication-service
  labels:
    app: myapplication
spec:
  selector:
    app: myapplication

  ports:
    - port: 80
      targetPort: 8080

  type: LoadBalancer
